# Application Settings
server.port=8080

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/flexzone_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Token configuration (64-byte Hex Encoded Secret Key for HS256)
flexzone.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
flexzone.jwt.expiration-ms=86400000

# Logging Level
logging.level.org.springframework.security=INFO
logging.level.com.flexzone=DEBUG
